# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Animation_lottie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Animation_lottie
pod 'lottie-ios'

end
