# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FilteringOperator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FilteringOperator

pod 'RxSwift'

  target 'FilteringOperatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FilteringOperatorUITests' do
    # Pods for testing
  end

end
